config/routes.rb
SuggestionBoxApp::Application.routes.draw do

	get "password_resets/new"

    #allow access to suggestion box via a short_name 
    #get "/suggestion_boxes/:suggestion_box_id/suggestions/new", to: "suggestions#new", as: ":short_name"

    #landing page default and confirmation
    root :to => 'invites#new'
    get 'thanks', to: "invites#thanks"

    #signup, login, logout
    get 'signup', to: "users#new", as: "signup"
    get 'login', to: "sessions#new", as: "login"
    get 'logout', to: "sessions#destroy", as: "logout"
    
    resources :invites, :organizations, :users, :sessions, :password_resets
    
    resources :suggestion_boxes do
        resources :suggestions
    end
    
    get ":short_name", to: "suggestions#new"

    default_url_options :host => "localhost:3000"
end

app/models/suggestion_box.rb
# == Schema Information
#
# Table name: suggestion_boxes
#
#  id              :integer          not null, primary key
#  name            :string(255)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  passcode        :string(255)
#  suggestion_id   :integer
#  organization_id :integer
#  short_name      :string(255)
#  owner_email     :string(255)
#  owner_name      :string(255)
#

class SuggestionBox < ActiveRecord::Base
  attr_accessible :name , :passcode, :short_name, :owner_email # :owner_name, :suggestions_attributes
  belongs_to :organization
  has_many :suggestions, :dependent => :destroy 
  #accepts_nested_attributes_for :suggestions #, allow_destroy: true
end

app/controllers/suggestion_boxes_controller.rb
      class SuggestionBoxesController < ApplicationController
        # GET /suggestion_boxes
        # GET /suggestion_boxes.json

        #before_filter :authorize, only: [:new, :edit, :update, :destroy]

        def index
          @suggestion_boxes = SuggestionBox.all

          respond_to do |format|
            format.html # index.html.erb
            format.json { render json: @suggestion_boxes }
          end
        end

        # GET /suggestion_boxes/1
        # GET /suggestion_boxes/1.json

      #get all the suggestions for this suggestion box
        def show
          @suggestion_box = SuggestionBox.find(params[:id])
          @suggestions = @suggestion_box.suggestions.all

          respond_to do |format|
            format.html # show.html.erb
            format.json { render json: @suggestion_box }
          end
        end

        # GET /suggestion_boxes/new
        # GET /suggestion_boxes/new.json
        def new
          @suggestion_box = SuggestionBox.new

          respond_to do |format|
            format.html # new.html.erb
            format.json { render json: @suggestion_box }
          end
        end

        # GET /suggestion_boxes/1/edit
        def edit
          @suggestion_box = SuggestionBox.find(params[:id])
        end

        # POST /suggestion_boxes
        # POST /suggestion_boxes.json
        def create
          @suggestion_box = SuggestionBox.new(params[:suggestion_box])

          respond_to do |format|
            if @suggestion_box.save
              format.html { redirect_to @suggestion_box, notice: "Your suggestion box has been created." }
              format.json { render json: @suggestion_box, status: :created, location: @suggestion_box }
            else
              format.html { render action: "new" }
              format.json { render json: @suggestion_box.errors, status: :unprocessable_entity }
            end
          end
        end

        # PUT /suggestion_boxes/1
        # PUT /suggestion_boxes/1.json
        def update
          @suggestion_box = SuggestionBox.find(params[:id])

          respond_to do |format|
            if @suggestion_box.update_attributes(params[:suggestion_box])
              format.html { redirect_to @suggestion_box, notice: 'Suggestion box was successfully updated.' }
              format.json { head :no_content }
            else
              format.html { render action: "edit" }
              format.json { render json: @suggestion_box.errors, status: :unprocessable_entity }
            end
          end
        end

        # DELETE /suggestion_boxes/1
        # DELETE /suggestion_boxes/1.json
        def destroy
          @suggestion_box = SuggestionBox.find(params[:id])
          @suggestion_box.destroy

          respond_to do |format|
            format.html { redirect_to suggestion_boxes_url }
            format.json { head :no_content }
          end
        end

        # def passcode
        #   @suggestion_box = SuggestionBox.find(params[:id])
        # end
      end

app/helpers/suggestion_boxes_helper.rb
module SuggestionBoxesHelper
end

app/views/suggestion_boxes/_form.html.erb
<%= form_for(@suggestion_box) do |f| %>
  <% if @suggestion_box.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@suggestion_box.errors.count, "error") %> prohibited this suggestion_box from being saved:</h2>

      <ul>
      <% @suggestion_box.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
    <div class="field">
    <%= f.label :short_name %><br />
    <%= f.text_field :short_name %>
  </div>
  <div class="field">
    <%= f.label :passcode %><br />
    <%= f.text_field :passcode %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/suggestion_boxes/edit.html.erb
<h1>Editing suggestion_box</h1>

<%= render 'form' %>

<%= link_to 'Show', @suggestion_box %> |
<%= link_to 'Back', suggestion_boxes_path %>

app/views/suggestion_boxes/index.html.erb
<header>
  <h1>Suggestion Boxes</h1>
</header>
<div id="content">
  <table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @suggestion_boxes.each do |suggestion_box| %>
  <tr>
    <td><%= suggestion_box.name %></td>
    <td><%= link_to 'Show', suggestion_box %></td>
    <td><%= link_to 'Edit', edit_suggestion_box_path(suggestion_box) %></td>
    <td><%= link_to 'Destroy', suggestion_box, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Suggestion box', new_suggestion_box_path %>
</div>

app/views/suggestion_boxes/new.html.erb
<header>
<h1>New Suggestion Box</h1>
</header>
<div id="content">
<%= render 'form' %>

<%= link_to 'Back', suggestion_boxes_path %>
</div>

app/views/suggestion_boxes/passcode-tmp.html.erb
Sorry that passcode didn't match the passcode for this suggestion box.  Please try again.
<%= form_for(@suggestion_box) do |f| %>
  <% if @suggestion_box.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@suggestion_box.errors.count, "error") %> prohibited this suggestion_box from being saved:</h2>

      <ul>
      <% @suggestion_box.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :passcode %><br />
    <%= f.text_field :entered_passcode %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/suggestion_boxes/passcode.html.erb
<h1>Please enter the <%= @suggestion_box.short_name %> suggestion box passcode</h1>
<%= form_for(@suggestion_box) do |f| %>
  <div class="field">
    <%= f.label "Please enter a passcode" %><br />
    <%= f.text_field :entered_passcode %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/suggestion_boxes/show.html.haml
%header
  = image_tag("http://placehold.it/50x50", :size => "50x50", :alt => "Org logo", class:"logo")
  %h1.title
    = @suggestion_box.short_name
    &nbsp;Suggestion Box
%p#notice= notice
%p
  = link_to "Post a new suggestion", new_suggestion_box_suggestion_path(@suggestion_box)
%table{:border => "1"}
  %tr
    %th
      Suggestion
    %th
      By
  - @suggestions.each do |suggestion|
    %tr
      %td
        = suggestion.message
      %td
        Posted by (Name+Email or "Anonymous")