config/routes.rb
SuggestionBoxApp::Application.routes.draw do

	get "password_resets/new"

    #allow access to suggestion box via a short_name 
    #get "/suggestion_boxes/:suggestion_box_id/suggestions/new", to: "suggestions#new", as: ":short_name"

    #landing page default and confirmation
    root :to => 'invites#new'
    get 'thanks', to: "invites#thanks"

    #signup, login, logout
    get 'signup', to: "users#new", as: "signup"
    get 'login', to: "sessions#new", as: "login"
    get 'logout', to: "sessions#destroy", as: "logout"
    
    resources :invites, :organizations, :users, :sessions, :password_resets
    
    resources :suggestion_boxes do
        resources :suggestions
    end
    
    get ":short_name", to: "suggestions#new"

    default_url_options :host => "localhost:3000"
end

app/models/organization.rb
# == Schema Information
#
# Table name: organizations
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Organization < ActiveRecord::Base
 attr_accessible :name #:suggestion_boxes_attributes
 has_many :members
 has_many :suggestion_boxes, :dependent => :destroy
 
 accepts_nested_attributes_for :suggestion_boxes

 before_save :lowercase_short_name

 def lowercase_short_name
 	self.short_name.downcase
 end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  # GET /organizations
  # GET /organizations.json

  before_filter :authenticate
  
  def index
    @organizations = Organization.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @organizations }
    end
  end

  # GET /organizations/1
  # GET /organizations/1.json
  def show
    @organization = Organization.find_by_short_name(params[:short_name])
    @suggestion = @organization.suggestions.build
    #@suggestion_box = @organization.suggestion_boxes.build

   #@organization = Organization.find_by_short_name(params[:short_name])
   #goal: display the information for the organization based on the short_name passed in the url
      #binding.pry
   #query Organization.suggestion_boxes.passcode

  # if :passcode.nil
  #   redirect_to :passcode
  # end
 #  @suggestion = @organization.suggestions.build

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @organization }
    end
  end

  # GET /organizations/new
  # GET /organizations/new.json
  def new
    @organization = Organization.new
    #@suggestions = @organization.suggestions.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @organization }
    end
  end

  # GET /organizations/1/edit
  def edit
    @organization = Organization.find(params[:id])
  end

  # POST /organizations
  # POST /organizations.json
  def create
    @organization = Organization.new(params[:organization])

    respond_to do |format|
      if @organization.save
        format.html { redirect_to @organization, notice: 'Organization was successfully created.' }
        format.json { render json: @organization, status: :created, location: @organization }
      else
        format.html { render action: "new" }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /organizations/1
  # PUT /organizations/1.json
  def update
    @organization = Organization.find(params[:id])

    respond_to do |format|
      if @organization.update_attributes(params[:organization])
        format.html { redirect_to @organization, notice: 'Organization was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organizations/1
  # DELETE /organizations/1.json
  def destroy
    @organization = Organization.find(params[:id])
    @organization.destroy

    respond_to do |format|
      format.html { redirect_to organizations_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/organizations/_footer.html.haml
%footer
  %hr
  %nav
    %ul.inline
      %li 
        = link_to 'Help', '#'
      %li
        Powered by
        = link_to 'Chirpybox', '#'

app/views/organizations/_form-tmp.html.haml
= form_for(@organization) do |f|
  - if @organization.errors.any?
    #error_explanation
      %h2
        = pluralize(@organization.errors.count, "error")
        prohibited this organization from being saved:
      %ul
        - @organization.errors.full_messages.each do |msg|
          %li= msg
  = f.fields_for :suggestions do |s|
    = s.label :suggestion_message
    %br/
    = s.text_area :suggestion_message
  .field
    = f.label :name
    %br/
    = f.text_field :name
  .field
    = f.label :short_name
    %br/
    = f.text_field :short_name
  .actions
    = f.submit

app/views/organizations/_form.html.haml
= form_for(@organization) do |f|
  - if @organization.errors.any?
    #error_explanation
      %h2
        = pluralize(@organization.errors.count, "error")
        prohibited this organization from being saved:
      %ul
        - @organization.errors.full_messages.each do |msg|
          %li= msg
  / = f.fields_for :suggestions do |s|
  /   = s.label :suggestion_message
  /   %br/
  /   = s.text_area :suggestion_message
  .field
    = f.label :name
    %br/
    = f.text_field :name
  .field
    -#= f.label :short_name
    %br/
    -#= f.text_field :short_name
  .actions
    = f.submit

app/views/organizations/_header.html.haml
%header
  = image_tag("/assets/bcl/bcl-logo-50px.png", :size => "45x50", :alt => "Brooklyn Creative League", class:"logo")
  %h1.title
    = @organization.short_name.upcase + " Suggestion Box"

app/views/organizations/_org_form.html.haml
= form_for(@organization) do |f|
  - if @organization.errors.any?
    #error_explanation
      %h2
        = pluralize(@organization.errors.count, "error")
        prohibited this organization from being saved:
      %ul
        - @organization.errors.full_messages.each do |msg|
          %li= msg
  /= f.fields_for :suggestions do |s|
  /  = s.label :suggestion_message
  /  %br/
  /  = s.text_area :suggestion_message
  .field
    = f.label :name
    %br/
    = f.text_field :name
  .field
    = f.label :short_name
    %br/
    = f.text_field :short_name
  .actions
    = f.submit

app/views/organizations/edit.html.erb
<h1>Editing organization</h1>

<%= render 'form' %>

<%= link_to 'Show', @organization %> |
<%= link_to 'Back', organizations_path %>

app/views/organizations/index.html.haml
%h1 Listing organizations
%table
  %tr
    %th Name
    %th
    %th
    %th
  - @organizations.each do |organization|
    %tr
      %td= organization.name
      %td= link_to 'Show', organization
      %td= link_to 'Edit', edit_organization_path(organization)
      %td= link_to 'Destroy', organization, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Organization', new_organization_path

app/views/organizations/new.html.erb
<h1>New organization</h1>

<%= render 'org_form' %>

<%= link_to 'Back', organizations_path %>

app/views/organizations/passcode.html.haml
= render 'header'
%p#notice= notice
%p
  %b "Please enter the passcode for this suggestion box passcode (you'll find it on the suggestion box signs posted around your workspace.):"
= form_for(@organization) do |f|
  = f.fields_for :suggestion_boxes do |s|
    = s.text_field :passcode, type:"password", placeholder:"Passcode"
    .actions
      = f.submit

app/views/organizations/show-tmp.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @organization.name %>
</p>


<%= link_to 'Edit', edit_organization_path(@organization) %> |
<%= link_to 'Back', organizations_path %>

app/views/organizations/show.html.haml
/ display a suggestion input field with an anonymous icon
/ on focus, display additional fields for this form
/ below the suggestion form, display a list of current/approved suggestions
= render 'header'
%p#notice= notice
%p
  /%b Name:
  /= @organization.name
  /(
  /= @organization.short_name
  /)
= form_for(@suggestion) do |f|
  = f.fields_for :suggestions do |s|
    /= s.label :suggestion_message
    %br/
    = s.text_area :suggestion_message, placeholder:"Drop a note in our suggestion box...", :rows => 6, :cols => 30
    %br/
    = check_box_tag "anonymous-suggestion", 1, false
    Post this suggestion anonymously
    / .field
    /   = f.label :name
    /   %br/
    /   = f.text_field :name
    / .field
    /   = f.label :short_name
    /   %br/
    /   = f.text_field :short_name
    .actions
      = f.submit "Post Suggestion"
/= link_to 'Edit', edit_organization_path(@organization)
/|
/\#{link_to 'Back', organizations_path}
.suggestions-list
  %hr
  %p.suggestion-list-header Vote and comment on other suggestions
  .suggestion
    %p.suggestion-snippet "Could we get a bigger whiteboard in the 3rd floor conference room?"
    .suggestion-vote
      = link_to '[Vote up icon]', '#' 
      = link_to '[Vote down icon]', '#' 
    .suggestion-reply
      = link_to '[Qty-replies icon]', '#'  
      = link_to '[Add-reply icon]', '#' 
= render 'footer'